In [1]:
import numpy as np

In [2]:
python_list = [1, 2, 3, 4, 5]
np_array=np.array(python_list)

In [3]:
print("Python List:", python_list)
print("NumPy Array:", np_array)

Python List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]


NO COMMAS!

In [15]:
crore=[i for i in range (10000000)]
np_array_crore=np.array(crore)

In [11]:
import time

In [12]:
start_list_time=time.time()
for i in crore:
    j=i+10
    crore[i]=j
end_list_time=time.time()
print(end_list_time-start_list_time)

0.4878058433532715


In [17]:

start_np_array_time=time.time()
result_np_array=np_array_crore + 10
end_np_array_time=time.time()
print(end_np_array_time-start_np_array_time)

0.018993616104125977


In [25]:
np_arr1=np.array([1,2,3.9])
print(np_arr1)

[1.  2.  3.9]


In [31]:
print(type(np.array))

<class 'builtin_function_or_method'>


In [34]:
np_arr2=np.array([1,2,3,4,5,6,7,8,9])

In [35]:
print(np_arr2[np_arr2>5])

[6 7 8 9]


In [36]:
np_arr2>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.array([6,7,8])
print(a+b)

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [47]:
a=np.array([1,2,3,4,5,6,7,8])


auto_reshaped=a.reshape(-1,2)
print(auto_reshaped)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [58]:

a=np.array([1,2,3,4])
b=np.array([4,5,6])
c=np.hstack((a,b))
print(c)

[1 2 3 4 4 5 6]
